### ISSUE TITLE
HNC: Look into manager pod imagePullPolicy

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#1025]
Currently we didn't specify `imagePullPolicy` and the manager pod with `latest` tag defaults to `always`:

```
    spec:
      containers:
      - args:
        - --webhook-server-port=9443
        - --metrics-addr=127.0.0.1:8080
        - --max-reconciles=10
        - --apiserver-qps-throttle=50
        - --enable-internal-cert-management
        - --cert-restart-on-secret-refresh
        command:
        - /manager
        image: gcr.io/{my-project}/hnc-manager:latest
        imagePullPolicy: Always
```

However, I still got pod created with cached image: `Container image "gcr.io/{my-project}/hnc-manager:latest" already present on machine` instead of `Successfully pulled image "gcr.io/{my-project}/hnc-manager:latest"`

Using the cached image for `latest` tag can be reproduced by commenting out line 222 in conversion_test.go (deleting the deployment before applying new manifest).
