### ISSUE TITLE
VC: apiserver certificate does not contain any IP SANs

### ISSUE THREAD

**Issue by munnerz** [kubernetes-sigs/multi-tenancy#1044]
When deploying a new virtual cluster and deploying a controller that communicates with the Kubernetes apiserver, I've found that the IP SANs field is not set on the x509 certificate used for serving by the "virtual" apiserver.

I do see that the IP SANs *can* be set here: https://github.com/kubernetes-sigs/multi-tenancy/blob/eb12a45cf2ff94d080666aa4479555f6f723615c/incubator/virtualcluster/pkg/controller/pki/pki.go#L73-L77

The `apiserverIPs` argument is determined here: https://github.com/kubernetes-sigs/multi-tenancy/blob/eb12a45cf2ff94d080666aa4479555f6f723615c/incubator/virtualcluster/pkg/controller/virtualcluster/master_provisioner_native.go#L291-L298

I'm not 100% certain why this `clusterIP` var doesn't get set, but now that I dig into this area of the code, I suspect that even if it did that there'd still be problems - notably, the IP address of the `kubernetes` Service in the *virtual* `default` namespace, i.e:

```
NAMESPACE                            NAME                                                         TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
prefix-39f5a2-cluster-default        kubernetes                                                   ClusterIP      10.109.131.115   <none>        443/TCP                  99m
```

From what I can tell reading this area of code, I *think* it would instead pull the cluster IP of the Service resources in the control plane namespace instead:

```
prefix-39f5a2-cluster                apiserver-svc                                                NodePort       10.110.219.228   <none>        6443:31568/TCP           100m
```

The exact error message I receive from my controller which is failing to run:

```
"error"="Get \"https://10.109.131.115:443/api?timeout=32s\": x509: cannot validate certificate for 10.109.131.115 because it doesn't contain any IP SANs"
```

(notice the IP ends in .115, which is the IP of the service in the 'default' namespace within the virtual cluster)

When inspecting the x509 certificate, I see the following SANs:

```
X509v3 Subject Alternative Name:
                DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, DNS:apiserver-svc.prefix-39f5a2-cluster, DNS:cluster
```

Can anyone confirm whether this is currently expected behaviour?

**Comment by charleszheng44** [comment]
@munnerz thanks for filing the issue. Yes, this is currently the expected behavior. This is due to the order (cretificates have to be created before starting the apiserver) of creating the tenant master. However, the svc/kuberentes under the default namespace is created after the apiserver is up and running. Therefore, we can't add its clusterIP into the certificate. If you want to try out the controller on the virtualcluster cluster, a workaround is setting the env `KUBERNETES_SERVICE_HOST` of the controller to `kuberentes` (the dns of the svc). Following is an example you can try out: 

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: podlister
spec:
  containers:
  - image: virtualcluster/podlister
    name: podlister
    command:
    - podlister-linux
    env:
    - name: KUBERNETES_SERVICE_HOST
      value: kubernetes
```

**Comment by charleszheng44** [comment]
@munnerz thanks for filing the issue. Yes, this is currently the expected behavior. This is due to the order (cretificates have to be created before starting the apiserver) of creating the tenant master. However, the svc/kuberentes under the default namespace is created after the apiserver is up and running. Therefore, we can't add its clusterIP into the certificate. If you want to try out the controller on the virtualcluster cluster, a workaround is setting the env KUBERNETES_SERVICE_HOST of the controller to kuberentes (the dns of the svc). Following is an example you can try out:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: podlister
spec:
  containers:
  - image: virtualcluster/podlister
    name: podlister
    command:
    - podlister-linux
    env:
    - name: KUBERNETES_SERVICE_HOST
      value: kubernetes
```
