### ISSUE TITLE
[MTB] Add Kyverno Policy - Require CAP_DROP_ALL

### ISSUE THREAD

**Issue by realshuting** [kubernetes-sigs/multi-tenancy#1110]

**Comment by JimBugwadia** [comment]
As a best practice, containers should drop all unnecessary capabilities:

```
        securityContext:
          capabilities:
            drop:
              - all
```

See: https://kubesec.io/basics/containers-securitycontext-capabilities-drop-index-all/

We need to add:
1. A benchmark
2. Validation tests
3. Kyverno and Gatekeeper/OPA policies that block workloads without a `capabilities drop all`.
