### ISSUE TITLE
HNC: Add NamespaceConditions to `kubectl hns config describe` too

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#1222]
Currently `kubectl hns config describe`  only shows HNCConfig's own conditions `status.conditions`, but not the `status.namespaceConditions`, e.g.
`kubectl get hncconfigurations.hnc.x-k8s.io config -oyaml` returns
```
status:
  namespaceConditions:
  - namespaces:
    - b
    - c
    - d
    reason: ParentMissing
    type: ActivitiesHalted
```
while they are not included in:
```
$ kubectl hns config describe
Synchronized types:
* Propagating: secrets (/v1)
* Propagating: rolebindings (rbac.authorization.k8s.io/v1)
* Propagating: roles (rbac.authorization.k8s.io/v1)

Conditions:
```
