### ISSUE TITLE
HNC: Limit conditions to list maximum 3 in v1alpha2

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#1226]
Part of #868 
See doc http://bit.ly/hnc_v1alpha2

There are 3 "conditions" fields in the HNC CRDs, `hc.status.conditions`, `hncconfig.status.conditions` and `hncconfig.status.namespaceConditions`.

I believe we only need to limit the length of the affected namespaces in `hncconfig.status.namespaceConditions`, since the other two only lists the local conditions that makes sense to list all. CMIIW

As for `hncconfig.status.namespaceConditions`, there's no good place to show in the CR that we only list first 3 affected namespaces if there are more. To make it clearer, I will
1. add a `numAffectedNamespaces` field to show the total number of affected namespaces;
2. add field description on `namespaces` in the CRD schema - "Namespaces is the list of affected namespaces in alphabetical order. Maximum of 3 namespaces will be listed if there are more than 3."

Thus, the `hncconfig.status.conditions` and `hncconfig.status.namespaceConditions` could look like this, with full list of `conditions` (possibly be more than 3) and maximum 3  in `namespaces` field in one namespace condition together with a total number of affected namespaces:
```
kind: HNCConfiguration
status:
  conditions:
  - lastTransitionTime: "1970-01-01T00:00:00Z"
    message: Resource "wrongtype1s" not found
    reason: ResourceNotFound
    status: "True"
    type: BadConfiguration
  - lastTransitionTime: "1970-01-01T00:00:00Z"
    message: Resource "wrongtype2s" not found
    reason: ResourceNotFound
    status: "True"
    type: BadConfiguration
  - lastTransitionTime: "1970-01-01T00:00:00Z"
    message: Resource "wrongtype3s" not found
    reason: ResourceNotFound
    status: "True"
    type: BadConfiguration
  - lastTransitionTime: "1970-01-01T00:00:00Z"
    message: Resource "wrongtype4s" not found
    reason: ResourceNotFound
    status: "True"
    type: BadConfiguration
  namespaceConditions:
  - numAffectedNamespaces: 4
    namespaces:
    - c
    - d
    - e
    reason: ParentMissing
    type: ActivitiesHalted
```
