### ISSUE TITLE
HNC: test NetworkPolicy integration with HNC

### ISSUE THREAD

**Issue by adrianludwin** [kubernetes-sigs/multi-tenancy#197]
/assign @srampal 

As discussed offline - play around with NetworkPolicy and HNC and verify both that:

- It gets copied and applied in descendant namespaces as expected
- You can use `namespaceSelector` to select subtrees for ingress and egress

An example `namespaceSelector` to select all subnamespaces of `foo` might be something like:

```
- namespaceSelector:
  - matchExpressions:
    - key: `foo.tree.hnc.x-k8s.io/depth`
      operator: Exists
```
