### ISSUE TITLE
Clarification: How the workloads are assigned for the tenant ?

### ISSUE THREAD

**Issue by rkamudhan** [kubernetes-sigs/multi-tenancy#24]
I am running the poc in the lab. Here is my understanding of the work regarding the tenant. Please help me to clarifies it.

Ownership
For resources created for a tenant, the OwnerReferences in the metadata points to the Tenant CR for maintaining the ownership. Currently, only namespaces are considered to adopt this reference. Additionally, a label is introduced on all resources owned by a tenant:

```multi-tenanct.k8s.io/tenant=tenant-name```

The Flow
- Cluster admin creates a cluster;
- Cluster admin creates all cluster-scoped policy objects in the cluster (e.g. ClusterRole, ClusterRoleBinding, PodSecurityPolicy etc.);
- Cluster admin creates NamespaceTemplate objects for per-tenant policies (e.g. Role, RoleBinding, NetworkPolicy, ResourceQuota etc.);
- Tenant Admin creates Tenant CR;
- The controller for Tenant CRD automatically creates the desired namespaces in Tenant object, populates the policy objects defined in NamespaceTemplate objects into the namespaces and also the access control resources (e.g. with RBAC: Role, RoleBinding) for admin identities.

Let's take tenant CRD is as below 
```
---
apiVersion: tenants.k8s.io/v1alpha1
kind: Tenant
metadata:
  name: tenant-a 
spec:
  namespaces:
      - name: ns-1
      - name: ns-2
```
This creates namespace as below:
```
# kubectl get ns
tenant-a-ns-1   Active   7d
tenant-a-ns-2   Active   7d
```
and pod spec will be something like this below:

```
apiVersion: v1
kind: Pod
metadata:
  name: dummy-pod
  annotations:
    multi-tenanct.k8s.io/tenant=tenant-a
spec:
  containers:
    - name: demo-container-1
      image: karlherler/pause 
      resources:
        limits:
          dummy/dummyDev: 2
```

How I can make sure that the workload dummy-pod is in tenant-a-ns1 or tenant-a-ns2? Am I missing some details here?

**Comment by easeway** [comment]
You don't need to specify annotation `multi-tenanct.k8s.io/tenant=tenant-a` on a Pod. As a Pod is a namespace-scoped resource, you always have to specify `namespace: namespace-name` in metadata, or use `kubectl -n namespace-name apply pod.yaml`. Otherwise, the Pod is defaulted to be created inside `default` namespace and in real world case, the tenant user won't have permission in `default` namespace and Pod creation will fail.

So, please fix your pod.yaml to include namespace name, e.g.

```
apiVersion: v1
kind: Pod
metadata:
  name: dummy-pod
  namespace: tenant-a-ns-1
```

or use `kubectl -n tenant-a-ns-1 apply pod.yaml`.
