### ISSUE TITLE
VC: livenessProbe for syncer

### ISSUE THREAD

**Issue by zhuangqh** [kubernetes-sigs/multi-tenancy#413]
export a health check port.

```
livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
```
