### ISSUE TITLE
MTB: Enable testing for multiple tenants with multiple namespaces

### ISSUE THREAD

**Issue by longngn** [kubernetes-sigs/multi-tenancy#532]
Current multi-tenancy benchmarks only allow testing for a single tenant and a single namespace. We should restructure the benchmark in some way to automate running tests for multiple tenants and each tenant with multiple namespaces. The config file could look like this:

```yaml
adminKubeconfig: path/to/admin/kubeconfig
tenants:
  - name: tenantA
    kubeconfig: path/to/tenantA/kubeconfig
    namespaces:
       - ns1
       - ns2
  - name: tenantB
    kubeconfig: path/to/tenantB/kubeconfig
    namespaces:
       - ns3
       - ns4
```
