### ISSUE TITLE
HNC: Add POD_NAMESPACE environment variable into pod spec

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#696]
In HNC admission controllers, when verifying the HNC SA user identity, it looked up the `POD_NAMESPACE` environment variable [here](https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/hnc/pkg/validators/hierarchy.go#L304) but the `env` is not declared in the pod spec.

The code uses a hard-coded `hnc-system` namespace if the env is not found. This bug won't cause any issue for now but better to fix in case anything changed in our pod spec, especially the namespace.

**Comment by adrianludwin** [comment]
Looks like we should be using the [downward AP](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/) for this.

**Comment by adrianludwin** [comment]
Also: we should log an error when we have to fall back on the default.

**Comment by adrianludwin** [comment]
On second thought, I don't think this is critical for v0.4.

**Comment by yiqigao217** [comment]
/remove-lifecycle stale

As stated before, it won't cause issue for now but better to fix in case of risks. It's used in hierarchy validator:
https://github.com/kubernetes-sigs/multi-tenancy/blob/26dab8a69fdf035be6eecf4052764e3ef8d0998f/incubator/hnc/internal/validators/hierarchy.go#L377

We should add the `env` in the pod spec like this [example](https://github.com/open-policy-agent/gatekeeper/blob/1de87b6d3c2ed3609e69b789d722e28285873861/config/manager/manager.yaml#L128-L133):
```
    spec:
      containers:
        - args: ...
          command: ...
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
```
