### ISSUE TITLE
HNC: CRD metadata.name validation for singletons

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#831]
Add kustomization patch to add metadata.name validation for singletons. With this, we can remove the validating webhooks on the singleton names and remove the `CritSingletonNameInvalid`  HNCConfiguration condition.

HNCConfiguration CRD:
```
CRD.spec.validation.openAPIV3Schema.properties.
metadata:
  type: object
  properties:
    name:
      type: string
      pattern: "^config$"
```

HierarchyConfiguration CRD:
```
CRD.spec.validation.openAPIV3Schema.properties.
metadata:
  type: object
  properties:
    name:
      type: string
      pattern: "^hierarchy$"
```

/assign @adrianludwin
